from .Common.StatusResult import StatusResult

from .AppSettings.AppSettingsSchema import AppSettingsSchema

from .Customer.CustomerUserProfileSchema import CustomerUserProfileSchema
from .Customer.CustomerOtpSchema import CustomerOtpSchema
from .Customer.CustomoerSessionSchema import CustomoerSessionSchema
from .Customer.CustomerPasswordHistSchema import CustomerPasswordHistSchema
from .Customer.CustomerPhotoSchema import CustomerPhotoSchema
from .Customer.CustomerComplaintsSchema import CustomerComplaintsSchema
from .Customer.CustomerChatSessionSchema import CustomerChatSessionSchema
from .Customer.CustomerChatMessageSchema import CustomerChatMessageSchema
from .Customer.CustomerAddMoneySchema import CustomerAddMoneySchema

from .System.SystemActivitySchema import SystemActivitySchema
from .System.SystemLogErrorSchema import SystemLogErrorSchema
from .System.SystemAdvertisementsSchema import SystemAdvertisementsSchema
from .System.SystemCaptchaLogSchema import SystemCaptchaLogSchema
from .System.SystemTableSlSchema import SystemTableSlSchema

from .Internal.LoginViewModelSchema import LoginViewModelSchema
from .Internal.NotificationViewModelSchema import NotificationViewModelSchema
from .Internal.ChangePasswordViewModelSchema import ChangePasswordViewModelSchema
from .Internal.ForgetPasswordViewModelSchema import ForgetPasswordViewModelSchema
from .Internal.RegistrationViewModelSchema import RegistrationViewModelSchema
from .Internal.ForgetUserIdViewModelSchema import ForgetUserIdViewModelSchema
from .Internal.FundTransferViewModelSchema import FundTransferViewModelSchema
from .Internal.CustomerActivityViewModelSchema import CustomerActivityViewModelSchema
from .Internal.ChatViewModelSchema import ChatRequestViewModelSchema, ChatResponseViewModelSchema
from .Internal.ComplaintViewModelSchema import ComplaintViewModelSchema
from .Internal.AppSettingViewModelSchema import AppSettingViewModelSchema
from .Internal.AddMoneyViewModelSchema import AddMoneyViewModelSchema

from .CBS.CBSCustomerInfoSchema import CBSCustomerInfoSchema
from .CBS.CBSCustomerAccountsSchema import CBSCustomerAccountsSchema
from .CBS.CBSAccountDetailsSchema import CBSAccountDetailsSchema
from .CBS.CBSAccountFullDetailsSchema import CBSAccountFullDetailsSchema
from .CBS.CBSAccountBalanceDetailsSchema import CBSAccountBalanceDetailsSchema
from .CBS.CBSCustomerAddressSchema import CBSCustomerAddressSchema
from .CBS.CBSCustomerEmailSchema import CBSCustomerEmailSchema
from .CBS.CBSCustomerPhoneSchema import CBSCustomerPhoneSchema
from .CBS.CBSCustomerFullInfoSchema import CBSCustomerFullInfoSchema
from .CBS.CBSAccountWiseTransLimitInfoSchema import CBSAccountWiseTransLimitInfoSchema
from .CBS.CBSTransactionHistorySchema import CBSTransactionHistorySchema
from .CBS.CBSBranchDetailsSchema import CBSBranchDetailsSchema
